---
- name: Provision workstation
  hosts: localhost
  connection: local
  vars_prompt:
    - name: first_name
      prompt: First name
      private: no
    - name: last_name
      prompt: Last name
      private: no
    - name: email
      prompt: Email
      private: no
    - name: signing_key
      prompt: Signing key
      private: no
  tasks:
    - name: Make local bin
      file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
    - name: Copy *rc
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item | basename }}"
        mode: u=rw,g=r,o=r
      with_fileglob: "conf/*rc"
    - name: Copy executables
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/{{ (item | basename | splitext)[0] }}"
        mode: u=rwx,g=rx,o=rx
      with_fileglob: "bin/*"
    # - name: copy gitconfig
    #   template:
    #     src: conf/gitconfig
    #     dest: "{{ asnible_env.HOME }}/.gitconfig"
