#!/bin/bash

archive=/run/media/jonathanlee/94726526-8fef-49c1-958f-aa3fd8cec49b
if [ ! -d "${archive}" ]; then
  echo "Archive not found: ${archive}" >/dev/stderr
  echo "Remember to open and mount the drive." >/dev/stderr
  exit 1
fi

userhome=/home/jonathanlee
set -x
backup --dry-run --archive "${archive}" create \
  --compression=gz \
  --exclude=__pycache__ \
  --exclude=*.pyc \
  --exclude=venv* \
  --exclude=virtualenv* \
  --exclude=.venv* \
  --exclude=.virtualenv* \
  --exclude=node_modules \
  --exclude=.npm \
  --exclude=.cache \
  --exclude=.vagrant \
  --exclude=*.synctex* \
  --exclude=.DS_Store \
  --exclude=*.aux \
  --exclude=*.lof \
  --exclude=*.fls \
  --exclude=*.fdb_latexmk \
  --exclude=*.pdfsync \
  --exclude=*.toc \
  --exclude=.atom/.apm \
  --exclude=.atom/compile-cache \
  --exclude=.pyenv \
  --exclude=.rvm \
  --exclude=.gem \
  --exclude=.gradle \
  --exclude=.node-gyp \
  --mount "${userhome}:/home" \
  "${userhome}" \
  /var/log/pacman.log
