#!/bin/bash

set -x
bin/backup.py --dry-run --archive=/tmp/archive restore \
  --mount /:/tmp/archive/test \
  --mount /uc-berkeley:${HOME}/uc-berkeley \
  --exclude=*.py \
  --exclude=*.pdf \
  --exclude=*ok*
